"""
LOGIX - Master Data Validation
Phase 04.2

Validates the 7 generated master datasets against
the schema actually generated by master_data.py.
"""

from pathlib import Path
import sys

import pandas as pd


# ============================================================
# PATH SETUP
# ============================================================

CURRENT_FILE = Path(__file__).resolve()

PYTHON_DIR = CURRENT_FILE.parents[1]
PROJECT_ROOT = CURRENT_FILE.parents[2]

if str(PYTHON_DIR) not in sys.path:
    sys.path.insert(0, str(PYTHON_DIR))


# ============================================================
# CONFIG
# ============================================================

from config import (
    RAW_DATA_DIR,
    NUM_CUSTOMERS,
    NUM_ADDRESSES,
    NUM_PRODUCTS,
    NUM_WAREHOUSES,
    NUM_DRIVERS,
    NUM_VEHICLES,
    NUM_DELIVERY_PARTNERS,
    PRODUCT_CATEGORIES,
    CUSTOMER_SEGMENTS,
)


# ============================================================
# GLOBAL RESULTS
# ============================================================

TOTAL_CHECKS = 0
PASSED_CHECKS = 0
FAILED_CHECKS = 0


# ============================================================
# RESULT HANDLERS
# ============================================================

def pass_check(message):
    global TOTAL_CHECKS, PASSED_CHECKS

    TOTAL_CHECKS += 1
    PASSED_CHECKS += 1

    print(f"  ✓ PASS | {message}")


def fail_check(message):
    global TOTAL_CHECKS, FAILED_CHECKS

    TOTAL_CHECKS += 1
    FAILED_CHECKS += 1

    print(f"  ✗ FAIL | {message}")


# ============================================================
# LOAD CSV
# ============================================================

def load_csv(filename):

    file_path = RAW_DATA_DIR / filename

    if not file_path.exists():

        fail_check(
            f"File missing: {filename}"
        )

        return None

    try:

        df = pd.read_csv(file_path)

        return df

    except Exception as error:

        fail_check(
            f"{filename}: unable to read CSV - {error}"
        )

        return None


# ============================================================
# ROW COUNT
# ============================================================

def check_row_count(
    df,
    filename,
    expected
):

    if df is None:
        return

    actual = len(df)

    if actual == expected:

        pass_check(
            f"{filename}: row count valid "
            f"({actual:,})"
        )

    else:

        fail_check(
            f"{filename}: expected "
            f"{expected:,}, found {actual:,}"
        )


# ============================================================
# COLUMN CHECK
# ============================================================

def check_columns(
    df,
    filename,
    required_columns
):

    if df is None:
        return

    missing = [
        column
        for column in required_columns
        if column not in df.columns
    ]

    if not missing:

        pass_check(
            f"{filename}: required columns present"
        )

    else:

        fail_check(
            f"{filename}: missing columns {missing}"
        )


# ============================================================
# PRIMARY KEY CHECK
# ============================================================

def check_primary_key(
    df,
    filename,
    column
):

    if df is None:
        return

    if column not in df.columns:
        return

    duplicate_count = (
        df[column]
        .duplicated()
        .sum()
    )

    null_count = (
        df[column]
        .isna()
        .sum()
    )

    if duplicate_count == 0:

        pass_check(
            f"{filename}: no duplicate {column}"
        )

    else:

        fail_check(
            f"{filename}: "
            f"{duplicate_count:,} duplicate {column}"
        )

    if null_count == 0:

        pass_check(
            f"{filename}: no NULL {column}"
        )

    else:

        fail_check(
            f"{filename}: "
            f"{null_count:,} NULL {column}"
        )


# ============================================================
# NULL CHECK
# ============================================================

def check_nulls(
    df,
    filename,
    critical_columns
):

    if df is None:
        return

    for column in critical_columns:

        if column not in df.columns:
            continue

        null_count = (
            df[column]
            .isna()
            .sum()
        )

        if null_count == 0:

            pass_check(
                f"{filename}.{column}: no NULL values"
            )

        else:

            fail_check(
                f"{filename}.{column}: "
                f"{null_count:,} NULL values"
            )


# ============================================================
# FOREIGN KEY CHECK
# ============================================================

def check_foreign_key(
    child_df,
    parent_df,
    child_file,
    child_column,
    parent_column
):

    if child_df is None or parent_df is None:
        return

    if (
        child_column not in child_df.columns
        or parent_column not in parent_df.columns
    ):
        return

    parent_values = set(
        parent_df[parent_column]
        .dropna()
    )

    invalid_values = (
        child_df.loc[
            ~child_df[child_column].isin(
                parent_values
            ),
            child_column
        ]
        .dropna()
        .unique()
    )

    if len(invalid_values) == 0:

        pass_check(
            f"{child_file}.{child_column}: "
            f"foreign key integrity valid"
        )

    else:

        fail_check(
            f"{child_file}.{child_column}: "
            f"{len(invalid_values):,} invalid references"
        )


# ============================================================
# ALLOWED VALUES
# ============================================================

def check_allowed_values(
    df,
    filename,
    column,
    allowed_values
):

    if df is None:
        return

    if column not in df.columns:
        return

    actual_values = set(
        df[column]
        .dropna()
        .unique()
    )

    invalid_values = (
        actual_values
        - set(allowed_values)
    )

    if len(invalid_values) == 0:

        pass_check(
            f"{filename}.{column}: "
            f"all values valid"
        )

    else:

        fail_check(
            f"{filename}.{column}: "
            f"invalid values {invalid_values}"
        )


# ============================================================
# NUMERIC RANGE CHECK
# ============================================================

def check_numeric_range(
    df,
    filename,
    column,
    minimum,
    maximum
):

    if df is None:
        return

    if column not in df.columns:
        return

    invalid = df[
        (df[column] < minimum)
        | (df[column] > maximum)
    ]

    if len(invalid) == 0:

        pass_check(
            f"{filename}.{column}: "
            f"range valid ({minimum}–{maximum})"
        )

    else:

        fail_check(
            f"{filename}.{column}: "
            f"{len(invalid):,} values outside range"
        )


# ============================================================
# UNIQUE COLUMN
# ============================================================

def check_unique_column(
    df,
    filename,
    column
):

    if df is None:
        return

    if column not in df.columns:
        return

    duplicate_count = (
        df[column]
        .duplicated()
        .sum()
    )

    if duplicate_count == 0:

        pass_check(
            f"{filename}.{column}: unique"
        )

    else:

        fail_check(
            f"{filename}.{column}: "
            f"{duplicate_count:,} duplicates"
        )


# ============================================================
# CUSTOMERS
# ============================================================

def validate_customers(df):

    filename = "customers.csv"

    print("\n[ CUSTOMERS ]")

    check_row_count(
        df,
        filename,
        NUM_CUSTOMERS
    )

    check_columns(
        df,
        filename,
        [
            "customer_id",
            "customer_name",
            "email",
            "phone",
            "gender",
            "customer_segment",
            "registration_date",
            "state",
            "city",
            "pincode",
            "preferred_payment_method",
            "is_active"
        ]
    )

    check_primary_key(
        df,
        filename,
        "customer_id"
    )

    check_nulls(
        df,
        filename,
        [
            "customer_id",
            "customer_name",
            "gender",
            "customer_segment",
            "registration_date",
            "state",
            "city",
            "pincode"
        ]
    )

    check_allowed_values(
        df,
        filename,
        "gender",
        [
            "Male",
            "Female",
            "Other"
        ]
    )

    check_allowed_values(
        df,
        filename,
        "customer_segment",
        CUSTOMER_SEGMENTS
    )

    check_allowed_values(
        df,
        filename,
        "preferred_payment_method",
        [
            "UPI",
            "Credit Card",
            "Debit Card",
            "Net Banking",
            "Cash on Delivery",
            "Wallet"
        ]
    )


# ============================================================
# ADDRESSES
# ============================================================

def validate_addresses(
    df,
    customers_df
):

    filename = "addresses.csv"

    print("\n[ ADDRESSES ]")

    check_row_count(
        df,
        filename,
        NUM_ADDRESSES
    )

    check_columns(
        df,
        filename,
        [
            "address_id",
            "customer_id",
            "address_type",
            "address_line",
            "city",
            "state",
            "pincode",
            "is_default"
        ]
    )

    check_primary_key(
        df,
        filename,
        "address_id"
    )

    check_nulls(
        df,
        filename,
        [
            "address_id",
            "customer_id",
            "city",
            "state",
            "pincode"
        ]
    )

    check_foreign_key(
        df,
        customers_df,
        filename,
        "customer_id",
        "customer_id"
    )

    check_allowed_values(
        df,
        filename,
        "address_type",
        [
            "Home",
            "Office",
            "Other"
        ]
    )


# ============================================================
# PRODUCTS
# ============================================================

def validate_products(df):

    filename = "products.csv"

    print("\n[ PRODUCTS ]")

    check_row_count(
        df,
        filename,
        NUM_PRODUCTS
    )

    check_columns(
        df,
        filename,
        [
            "product_id",
            "product_name",
            "category",
            "brand",
            "unit_price",
            "weight_kg",
            "supplier",
            "reorder_level",
            "is_active"
        ]
    )

    check_primary_key(
        df,
        filename,
        "product_id"
    )

    check_nulls(
        df,
        filename,
        [
            "product_id",
            "product_name",
            "category",
            "unit_price",
            "weight_kg",
            "reorder_level"
        ]
    )

    check_allowed_values(
        df,
        filename,
        "category",
        PRODUCT_CATEGORIES
    )

    check_numeric_range(
        df,
        filename,
        "unit_price",
        0.01,
        100000
    )

    check_numeric_range(
        df,
        filename,
        "weight_kg",
        0.01,
        30
    )

    check_numeric_range(
        df,
        filename,
        "reorder_level",
        1,
        100
    )


# ============================================================
# WAREHOUSES
# ============================================================

def validate_warehouses(df):

    filename = "warehouses.csv"

    print("\n[ WAREHOUSES ]")

    check_row_count(
        df,
        filename,
        NUM_WAREHOUSES
    )

    check_columns(
        df,
        filename,
        [
            "warehouse_id",
            "warehouse_name",
            "warehouse_type",
            "city",
            "state",
            "pincode",
            "capacity_units",
            "manager_name",
            "operating_hours",
            "is_active"
        ]
    )

    check_primary_key(
        df,
        filename,
        "warehouse_id"
    )

    check_nulls(
        df,
        filename,
        [
            "warehouse_id",
            "warehouse_name",
            "city",
            "state",
            "capacity_units"
        ]
    )

    check_allowed_values(
        df,
        filename,
        "warehouse_type",
        [
            "Regional",
            "Central",
            "Fulfillment",
            "Distribution"
        ]
    )

    check_numeric_range(
        df,
        filename,
        "capacity_units",
        1,
        1_000_000
    )


# ============================================================
# DRIVERS
# ============================================================

def validate_drivers(df):

    filename = "drivers.csv"

    print("\n[ DRIVERS ]")

    check_row_count(
        df,
        filename,
        NUM_DRIVERS
    )

    check_columns(
        df,
        filename,
        [
            "driver_id",
            "driver_name",
            "phone",
            "license_number",
            "experience_years",
            "rating",
            "city",
            "employment_type",
            "status"
        ]
    )

    check_primary_key(
        df,
        filename,
        "driver_id"
    )

    check_nulls(
        df,
        filename,
        [
            "driver_id",
            "driver_name",
            "phone",
            "license_number",
            "experience_years",
            "rating",
            "city",
            "employment_type",
            "status"
        ]
    )

    check_numeric_range(
        df,
        filename,
        "experience_years",
        1,
        20
    )

    check_numeric_range(
        df,
        filename,
        "rating",
        2.5,
        5.0
    )

    check_allowed_values(
        df,
        filename,
        "employment_type",
        [
            "Full Time",
            "Contract",
            "Partner"
        ]
    )

    check_allowed_values(
        df,
        filename,
        "status",
        [
            "Active",
            "Inactive",
            "On Leave"
        ]
    )


# ============================================================
# VEHICLES
# ============================================================

def validate_vehicles(df):

    filename = "vehicles.csv"

    print("\n[ VEHICLES ]")

    check_row_count(
        df,
        filename,
        NUM_VEHICLES
    )

    check_columns(
        df,
        filename,
        [
            "vehicle_id",
            "vehicle_number",
            "vehicle_type",
            "capacity_kg",
            "fuel_type",
            "model_year",
            "driver_id",
            "status"
        ]
    )

    check_primary_key(
        df,
        filename,
        "vehicle_id"
    )

    check_unique_column(
        df,
        filename,
        "vehicle_number"
    )

    check_nulls(
        df,
        filename,
        [
            "vehicle_id",
            "vehicle_number",
            "vehicle_type",
            "capacity_kg",
            "fuel_type",
            "model_year",
            "driver_id",
            "status"
        ]
    )

    check_allowed_values(
        df,
        filename,
        "vehicle_type",
        [
            "Bike",
            "Van",
            "Mini Truck",
            "Truck",
            "Heavy Truck"
        ]
    )

    check_allowed_values(
        df,
        filename,
        "fuel_type",
        [
            "Diesel",
            "Petrol",
            "CNG",
            "Electric"
        ]
    )

    check_allowed_values(
        df,
        filename,
        "status",
        [
            "Active",
            "Maintenance",
            "Inactive"
        ]
    )

    check_numeric_range(
        df,
        filename,
        "capacity_kg",
        1,
        20000
    )

    check_numeric_range(
        df,
        filename,
        "model_year",
        2018,
        2026
    )

    check_foreign_key(
        df,
        None,
        filename,
        "driver_id",
        "driver_id"
    )


# ============================================================
# DELIVERY PARTNERS
# ============================================================

def validate_delivery_partners(df):

    filename = "delivery_partners.csv"

    print("\n[ DELIVERY PARTNERS ]")

    check_row_count(
        df,
        filename,
        NUM_DELIVERY_PARTNERS
    )

    check_columns(
        df,
        filename,
        [
            "partner_id",
            "partner_name",
            "service_type",
            "coverage_type",
            "base_cost_per_km",
            "rating",
            "contact_phone",
            "status"
        ]
    )

    check_primary_key(
        df,
        filename,
        "partner_id"
    )

    check_unique_column(
        df,
        filename,
        "partner_name"
    )

    check_nulls(
        df,
        filename,
        [
            "partner_id",
            "partner_name",
            "service_type",
            "coverage_type",
            "base_cost_per_km",
            "rating",
            "status"
        ]
    )

    check_allowed_values(
        df,
        filename,
        "service_type",
        [
            "Standard",
            "Express",
            "Same Day",
            "Hyperlocal"
        ]
    )

    check_allowed_values(
        df,
        filename,
        "coverage_type",
        [
            "Local",
            "Regional",
            "National"
        ]
    )

    check_allowed_values(
        df,
        filename,
        "status",
        [
            "Active",
            "Inactive"
        ]
    )

    check_numeric_range(
        df,
        filename,
        "base_cost_per_km",
        0.01,
        100
    )

    check_numeric_range(
        df,
        filename,
        "rating",
        3.0,
        5.0
    )


# ============================================================
# DATASET SUMMARY
# ============================================================

def print_dataset_summary(datasets):

    print("\n")
    print("=" * 70)
    print("DATASET SUMMARY")
    print("=" * 70)

    for filename, df in datasets.items():

        if df is not None:

            print(
                f"{filename:<30}"
                f"{len(df):>10,} rows"
            )


# ============================================================
# FINAL REPORT
# ============================================================

def print_final_report():

    print("\n")
    print("=" * 70)
    print("VALIDATION REPORT")
    print("=" * 70)

    print(
        f"Total Checks : {TOTAL_CHECKS}"
    )

    print(
        f"Passed       : {PASSED_CHECKS}"
    )

    print(
        f"Failed       : {FAILED_CHECKS}"
    )

    print("-" * 70)

    if FAILED_CHECKS == 0:

        print(
            "STATUS       : ✅ VALIDATION PASSED"
        )

        print(
            "\nMaster data is ready for "
            "transactional data generation."
        )

        return True

    else:

        print(
            "STATUS       : ❌ VALIDATION FAILED"
        )

        print(
            "\nFix the failed checks before "
            "generating transactional data."
        )

        return False

def main():

    print()
    print("=" * 70)
    print("LOGIX MASTER DATA VALIDATION")
    print("=" * 70)

    # ========================================================
    # LOAD DATA
    # ========================================================

    customers = load_csv(
        "customers.csv"
    )

    addresses = load_csv(
        "addresses.csv"
    )

    products = load_csv(
        "products.csv"
    )

    warehouses = load_csv(
        "warehouses.csv"
    )

    drivers = load_csv(
        "drivers.csv"
    )

    vehicles = load_csv(
        "vehicles.csv"
    )

    partners = load_csv(
        "delivery_partners.csv"
    )

    datasets = {
        "customers.csv": customers,
        "addresses.csv": addresses,
        "products.csv": products,
        "warehouses.csv": warehouses,
        "drivers.csv": drivers,
        "vehicles.csv": vehicles,
        "delivery_partners.csv": partners
    }

    # ========================================================
    # VALIDATE
    # ========================================================

    validate_customers(
        customers
    )

    validate_addresses(
        addresses,
        customers
    )

    validate_products(
        products
    )

    validate_warehouses(
        warehouses
    )

    validate_drivers(
        drivers
    )

    validate_vehicles(
        vehicles
    )

    validate_delivery_partners(
        partners
    )

    # ========================================================
    # SUMMARY
    # ========================================================

    print_dataset_summary(
        datasets
    )

    # ========================================================
    # FINAL REPORT
    # ========================================================

    validation_passed = print_final_report()

    if not validation_passed:
        sys.exit(1)


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()

